/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Grid: typeof import('./src/components/Grid.vue')['default']
    Image: typeof import('./src/components/Image.vue')['default']
  }
}
